### ISSUE TITLE
Failure to capture

### ISSUE THREAD

**Issue by X-Ryl669** [cesanta/slre#14]
Add this to the end of the unit_test.c:
```
  {
    /* Example more complex regular expression */
    static const char * str = "aa 1234 xy\nz";
    static const char * regex = "aa ([0-9]*) *([x-z]*)";
    struct slre_cap caps[2];
    ASSERT(slre_match(regex, str, strlen(str), caps, 2) > 0);
    ASSERT(caps[0].len == 4);
    ASSERT(caps[1].len == 2); /* Fails here */
  }
```
During " *" evaluation, it does capture correctly the second item, but the end of the loop -look for zero time- overwrite the captured item even if it failed to match.

**Comment by sebgod** [comment]
@X-Ryl669 May I ask if you have already a patch in a fork of this repository? I'd be very intersted in forking this project when the maintainer is not active any longer.

**Comment by X-Ryl669** [comment]
@cpq You made a mistake in your commit, it's: "if (n2 < 0" and not "if (n1 < 0"

**Comment by cpq** [comment]
Thank you @X-Ryl669 & @sebgod
