### ISSUE TITLE
Spaces at the end - but not required

### ISSUE THREAD

**Issue by wordnice** [cesanta/slre#20]
Hello,

is this part of perl regex or it is bug (I am regex newbie)? Look at the spaces at the end in output.

Input: `Heooo Heoa Heoo Heloa Helo Heloo Hello Helloo`
Regex used: `(He(l*)?o[^a])`

Output:
```
	[Heoo]
	[Heoo]
	[Helo ]
	[Heloo]
	[Hello ]
	[Helloo]
```

Code used: https://github.com/wordnice/Trnavka/blob/d2e6e03d664366017050a914a929566f4b7fa92b/src/Main.c#L81
(TRN_ is only prefix; Long is long long; REEntry is slre_cap)

Thanks!

**Comment by cpq** [comment]
Could you run perl against your regex & input please?

**Comment by sgbeal** [comment]
@wordnice the spaces are matching the [^a] part so yes, they are expected.

**Comment by wordnice** [comment]
OK, thanks!
This is briliant library! Thank you for writing it!
