### ISSUE TITLE
Flags fix

### ISSUE THREAD

**Issue by wordnice** [cesanta/slre#22]
`slre.c:169`
As far as SLRE_IGNORE_CASE is flag, shouldn't be this
```c
      result = info->flags && SLRE_IGNORE_CASE ?
```
replaced by
```c
      result = info->flags & SLRE_IGNORE_CASE ? ...
```

Thanks

**Comment by cpq** [comment]
Correct, pushed https://github.com/cesanta/slre/commit/521f750aa955d9f7a80d5555934a463c7d587375 , thanks!
