### ISSUE TITLE
Stricter C/C++11 standard compatibility - resolve warnings

### ISSUE THREAD

**Issue by breznak** [cesanta/slre#28]
aim to compile with `-Werror`

- [x] `cast-equal` 
- [ ] `assuming signed overflow does not occur when simplifying conditional to constant [-Werror=strict-overflow]`

**Comment by cpq** [comment]
We'll integrate your patch, thank you!

**Comment by breznak** [comment]
@cpq great, thanks! Can you solve the other part? 

> assuming signed overflow does not occur when simplifying conditional to constant [-Werror=strict-overflow]

I did not find an example how to resolve that warning..

**Comment by cpq** [comment]
No idea what that warning means :)
